### ISSUE TITLE
Connect chat with Code for Australia

### ISSUE THREAD

**Issue by graceohara** [Code-for-All/matterbridge-config#1]
## What is your Slack's url?

https://codeforaustralia.slack.com

## List channels from Code for All that you want to have in your organization

**Format: Code for Australia Channel <<-->> Code for All Channel**
#code-for-all-news <<-->> #readingroom
#code-for-all-chatter <<-->> #general
#general <<-->> #code-for-australia

## Configuring the bot

Did you create a bot or invited Krzysztof to your org as mentioned in point 2 below:
https://github.com/Code-for-All/matterbridge-config/blob/master/README.md#adding-new-organizations-and-channels

**Yes** - Invited Krzysztof to the Code for Australia Slack

Did you create relevant channels in your org and invited there bot (`/invite @matterbridge` command) or invited Krzysztof to your org do that?

**Yes**

**Comment by graceohara** [comment]
Woooooo this is my first issue on GitHub! :D

**Comment by KrzysztofMadejski** [comment]
Congratulations @graceohara !

I sent a request to install the bot in your Slack. It's called Matterbridge-CfAll

**Comment by graceohara** [comment]
Yay! Thank you :D I tried to Install it but I get the following error message...

`OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : 
Allowed URI : none specified
`

We've approved it for members to add so you should have permission to install it now, if I'm doing something wrong.

**Comment by KrzysztofMadejski** [comment]
Yes, I can continue now. Thanks!
